#!/usr/bin/env bash

# Enable debugging
#set -x


export STEAMCMDDIR=/home/steam/steamcmd
cd $STEAMCMDDIR

# Print the user we're currently running as
echo "Running as user: $(whoami)"
echo "steamcmd folder is: $STEAMCMDDIR"
echo "Current directory: $(pwd)"

# Retake ownership of the steamcmd + rust folder if it was mounted as root with LXC for example
sudo  /app/chown_steam.sh

mkdir -p /home/steam/.ssh
# For ease of management of this container, we authorize 
# any authorized keys for the root user to also log in directly with
# the less privileged steam user if wanted.
# Use case: LXC on proxmox has built-in functionality to allow keys but that is only set for the root user
# It is convenient to be able to directly login as the steam user without having to so sudo -s -u steam for example
touch /home/steam/.ssh/authorized_keys
sudo /app/cat_authkeys.sh > /home/steam/.ssh/authorized_keys
#echo "Starting openssh server"
#/usr/sbin/sshd -p 22 -f /app/sshd_config

RUST_DEFAULT_ENV_FILE=/app/rust.default.env
# Load default env file to set default values that may not be overriden in custom env file
set -o allexport
source $RUST_DEFAULT_ENV_FILE
set +o allexport

echo "Copying rust data folder overrides if they don't already exists..."
cp -R --update=none /app/default_rust_data_overrides/*  $STEAMCMDDIR/rust/
RUST_ENV_FILE=$STEAMCMDDIR/rust/rust.env
if ! [ -f $RUST_ENV_FILE ]; then
	echo "Configuring a default rust.env file in $RUST_ENV_FILE, please edit and restart the container!"
	NEW_SEED=$(shuf -i 1-2147483647 -n 1)
	while read line; do
		var=$(echo $line | cut -d= -f1)
		if [ $var == "RUST_RCON_PASSWORD" ]; then
			echo "${var}=$(tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 12)" >> $RUST_ENV_FILE
		elif [ $var == "RUST_SERVER_SEED" ]; then
			echo "${var}=$NEW_SEED" >> $RUST_ENV_FILE
		else
			echo "${line}" >> $RUST_ENV_FILE
		fi
	done <$RUST_DEFAULT_ENV_FILE 
fi
if  [ -f $RUST_ENV_FILE ]; then
  echo "$RUST_ENV_FILE file is mounted and will be used instead on container start&restart (make sure all strings with spaces are surrounded by double quotes if you see errors after this!)"
  echo "Using the following configuration (with interpreted actual values):"
  echo "=================================="
  set -o allexport
  source $RUST_ENV_FILE
  #cat $RUST_ENV_FILE
  set +o allexport
	while read p; do
		var=$(echo $p | cut -d= -f1)
		echo "${var}=\"${!var}\""
	done <$RUST_ENV_FILE
  echo "=================================="
else
  echo "$RUST_ENV_FILE is not mounted inside the container. Will use the exported rust environment config from the container start command."
  echo "Consider passing a mounted file $RUST_ENV_FILE to the container to apply the latest configuration on game restart"
fi

# Define the exit handler (hint: it doesn't handle anything...)
exit_handler()
{
	echo "Shutdown signal received"
}

# Trap specific signals and forward to the exit handler
trap 'exit_handler' SIGINT SIGTERM

# Rust includes a 64-bit version of steamclient.so, so we need to tell the OS where it exists
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$STEAMCMDDIR/rust/RustDedicated_Data/Plugins/x86_64

# Install/update steamcmd
echo "Installing/updating steamcmd"
curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf - -C $STEAMCMDDIR

while [ ! -f $STEAMCMDDIR/steamcmd.sh ]; do
	echo "steamcmd did not download, trying again in 1 second, network may not be up yet..."
	sleep 1
	curl -sqL "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz" | tar zxvf - -C $STEAMCMDDIR
done

# Define the install/update function
install_or_update()
{
	# Install Rust from install.txt
	echo "Installing or updating Rust.. (this might take a while, be patient)"
	bash $STEAMCMDDIR/steamcmd.sh +runscript /app/install.txt

	# Terminate if exit code wasn't zero
	if [ $? -ne 0 ]; then
		echo "Exiting, steamcmd install or update failed!"
		exit 1
	fi
}

# Remove old lock files (used by restart_app/ and update_check.sh)
rm -fr /tmp/*.lock

# Create the necessary folder structure
if [ ! -d "$STEAMCMDDIR/rust" ]; then
	echo "Missing $STEAMCMDDIR/rust, creating.."
	mkdir -p $STEAMCMDDIR/rust
fi
if [ ! -d "$STEAMCMDDIR/rust/server/${RUST_SERVER_IDENTITY}" ]; then
	echo "Missing $STEAMCMDDIR/rust/server/${RUST_SERVER_IDENTITY}, creating.."
	mkdir -p "$STEAMCMDDIR/rust/server/${RUST_SERVER_IDENTITY}"
fi

if [ -f "$STEAMCMDDIR/rust/force_full_wipe" ] || [ -f "$STEAMCMDDIR/rust/force_map_wipe" ]; then
        echo "Processing manual WIPE trigger file..."
        DATE_TIME=$(date +"%Y%m%dT%H%M%S")
	mkdir -p $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}
	mkdir -p $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/server/${RUST_SERVER_IDENTITY}
        mkdir -p $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/carbon/data/Backpacks
	mv $STEAMCMDDIR/rust/carbon/data/Backpacks/* $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/carbon/data/Backpacks/
	if [ -f "$STEAMCMDDIR/rust/force_full_wipe" ]; then
	        echo "This is a FULL wipe..."
        	mv $STEAMCMDDIR/rust/server/${RUST_SERVER_IDENTITY}/player.blueprints.* $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/server/${RUST_SERVER_IDENTITY}/
	else
	        echo "This is a MAP wipe..."
        	cp $STEAMCMDDIR/rust/server/${RUST_SERVER_IDENTITY}/player.blueprints.* $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/server/${RUST_SERVER_IDENTITY}/
	fi
       	cp $STEAMCMDDIR/rust/server/${RUST_SERVER_IDENTITY}/player.tokens.* $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/server/${RUST_SERVER_IDENTITY}/

        mv $STEAMCMDDIR/rust/server/${RUST_SERVER_IDENTITY}/proceduralmap.* $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/server/${RUST_SERVER_IDENTITY}/
        mv $STEAMCMDDIR/rust/server/${RUST_SERVER_IDENTITY}/sv.files.* $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/server/${RUST_SERVER_IDENTITY}/
        mv $STEAMCMDDIR/rust/server/${RUST_SERVER_IDENTITY}/player.states.* $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/server/${RUST_SERVER_IDENTITY}/
        mv $STEAMCMDDIR/rust/server/${RUST_SERVER_IDENTITY}/player.deaths.* $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/server/${RUST_SERVER_IDENTITY}/
        mv $STEAMCMDDIR/rust/server/${RUST_SERVER_IDENTITY}/player.identities.* $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/server/${RUST_SERVER_IDENTITY}/
	rm -f $STEAMCMDDIR/rust/force_full_wipe
	rm -f $STEAMCMDDIR/rust/force_map_wipe
        echo "Manual WIPE completed. Previous files were moved under $STEAMCMDDIR/rust/backup_manual_wipe/${DATE_TIME}/"
else
	echo "There is no manual wipe trigger to process ($STEAMCMDDIR/rust/force_full_wipe or $STEAMCMDDIR/rust/force_map_wipe files are not present). Proceeding with normal startup..."
fi



# Check which branch to use
if [ ! -z ${RUST_BRANCH+x} ]; then
	echo "Using branch arguments: $RUST_BRANCH"

	# Add "-beta" if necessary
	INSTALL_BRANCH="${RUST_BRANCH}"
	if [ ! "$RUST_BRANCH" == "public" ]; then
	    INSTALL_BRANCH="-beta ${RUST_BRANCH}"
	fi
	sed -i "s/app_update 258550.*validate/app_update 258550 $INSTALL_BRANCH validate/g" /app/install.txt
else
	sed -i "s/app_update 258550.*validate/app_update 258550 validate/g" /app/install.txt
fi

# Disable auto-update if start mode is 2
if [ "$RUST_START_MODE" = "2" ]; then
	# Check that Rust exists in the first place
	if [ ! -f "$STEAMCMDDIR/rust/RustDedicated" ]; then
		install_or_update
	else
		echo "Rust seems to be installed, skipping automatic update.."
	fi
else
	install_or_update

	# Run the update check if it's not been run before
	if [ ! -f "$STEAMCMDDIR/rust/build.id" ]; then
		/app/update_check.sh
	else
		OLD_BUILDID="$(cat $STEAMCMDDIR/rust/build.id)"
		STRING_SIZE=${#OLD_BUILDID}
		if [ "$STRING_SIZE" -lt "6" ]; then
			/app/update_check.sh
		fi
	fi
fi

# Ensure only Oxide or Carbon is selected, not both.
if [ "$RUST_OXIDE_ENABLED" = "1" ] && [ "$RUST_CARBON_ENABLED" = "1" ]; then
	echo "You need to select either Carbon or Oxide for your Plugins, can't enable both."
	exit 1
fi

# Check if Oxide is enabled
if [ "$RUST_OXIDE_ENABLED" = "1" ]; then
	# Next check if Oxide doesn't' exist, or if we want to always update it
	INSTALL_OXIDE="0"
	if [ ! -f "$STEAMCMDDIR/rust/CSharpCompiler.x86_x64" ]; then
		INSTALL_OXIDE="1"
	fi
	if [ "$RUST_OXIDE_UPDATE_ON_BOOT" = "1" ]; then
		INSTALL_OXIDE="1"
	fi

	# If necessary, download and install latest Oxide
	if [ "$INSTALL_OXIDE" = "1" ]; then
		echo "Downloading and installing latest Oxide.."
		OXIDE_URL="https://umod.org/games/rust/download/develop"
		curl -sL $OXIDE_URL | bsdtar -xvf- -C $STEAMCMDDIR/rust/
		chmod 755 $STEAMCMDDIR/rust/CSharpCompiler.x86_x64 > /dev/null 2>&1 &
	fi
fi

if [ "$RUST_CARBON_ENABLED" = "1" ]; then
	CARBON_BASE_URL="https://github.com/CarbonCommunity/Carbon.Core/releases/download/"
	INSTALL_CARBON="0"
	if [ ! -f "$STEAMCMDDIR/rust/carbon/managed/Carbon.dll" ]; then
		INSTALL_CARBON="1"
	fi

	if [ "$RUST_CARBON_UPDATE_ON_BOOT" = "1" ]; then
		INSTALL_CARBON="1"
	fi

	if [ "$INSTALL_CARBON" = "1" ]; then
		echo "Downloading and installing latest Carbon.."

		case $RUST_BRANCH in
			"staging")
				echo "Downloading Rust Staging Release.."
				CARBON_URL="${CARBON_BASE_URL}rustbeta_staging_build/Carbon.Linux.Debug.tar.gz"
				;;
			"aux01")
				echo "Downloading Rust AUX01 Release.."
				CARBON_URL="${CARBON_BASE_URL}rustbeta_aux01_build/Carbon.Linux.Debug.tar.gz"
				;;
			"aux02")
				echo "Downloading Rust AUX02 Release.."
				CARBON_URL="${CARBON_BASE_URL}rustbeta_aux02_build/Carbon.Linux.Debug.tar.gz"
				;;
			*)
				if [ ! -z ${RUST_CARBON_BRANCH+x} ]; then
					case $RUST_CARBON_BRANCH in
						"preview")
							echo "Downloading preview release.."
							CARBON_URL="${CARBON_BASE_URL}preview_build/Carbon.Linux.Debug.tar.gz"
							;;
						"edge")
							echo "Downlaoding edge release.."
							CARBON_URL="${CARBON_BASE_URL}edge_build/Carbon.Linux.Debug.tar.gz"
							;;
						*)
							echo "Downloading Rust Production Release.."
							CARBON_URL="${CARBON_BASE_URL}production_build/Carbon.Linux.Release.tar.gz"
							;;
					esac
				else
					echo "Downloading Rust Production Release.."
					CARBON_URL="${CARBON_BASE_URL}production_build/Carbon.Linux.Release.tar.gz"
				fi
				;;
		esac
		curl -sL $CARBON_URL | tar -xzvf- -C $STEAMCMDDIR/rust/
		chmod 755 $STEAMCMDDIR/rust/carbon/tools/environment.sh
	fi
fi

# Start mode 1 means we only want to update
if [ "$RUST_START_MODE" = "1" ]; then
	echo "Exiting, start mode is 1.."
	exit
fi

# Remove extra whitespace from startup command
RUST_STARTUP_COMMAND=$(echo "$RUST_SERVER_STARTUP_ARGUMENTS" | tr -s " ")

# Add RCON support if necessary
if [ ! -z ${RUST_RCON_PORT+x} ]; then
	RUST_STARTUP_COMMAND="$RUST_STARTUP_COMMAND +rcon.port $RUST_RCON_PORT"
fi
if [ ! -z ${RUST_RCON_PASSWORD+x} ]; then
	RUST_STARTUP_COMMAND="$RUST_STARTUP_COMMAND +rcon.password $RUST_RCON_PASSWORD"
fi

# Setup the rcon web
if [ ! -z ${RUST_RCON_WEB+x} ]; then
	RUST_STARTUP_COMMAND="$RUST_STARTUP_COMMAND +rcon.web $RUST_RCON_WEB"
	if [ "$RUST_RCON_WEB" = "1" ]; then
		# Fix the webrcon (customizes a few elements)
		bash -c "RUST_RCON_SECURE_WEBSOCKET=${RUST_RCON_SECURE_WEBSOCKET} /app/fix_conn.sh"
	fi
fi

# Start the scheduler (only if update checking is enabled)
if [ "$RUST_UPDATE_CHECKING" = "1" ]; then
	echo "Starting scheduled task manager.."
	node /app/scheduler_app/app.js &
fi

# Start the heartbeat(only if enabled)
if [ "$RUST_HEARTBEAT" = "1" ]; then
	echo "Starting heartbeat.."
	node /app/heartbeat_app/app.js &
fi

# Set the working directory
cd $STEAMCMDDIR/rust

# Run the server
echo "Starting Rust.."

# Preparing arguments
function add_argument_pair {
        local -n arr=$1
        if  [ ! -z "${!3}" ]; then
                  arr+=("${2}");
                  arr+=("${!3}");
        fi
}

ARGUMENTS=()

add_argument_pair ARGUMENTS "+server.port" "RUST_SERVER_PORT"
add_argument_pair ARGUMENTS "+server.queryport" "RUST_SERVER_QUERYPORT"
add_argument_pair ARGUMENTS "+server.identity" "RUST_SERVER_IDENTITY"

if [ "$RUST_SERVER_CUSTOMMAP_ENABLED" = "1" ]; then
	add_argument_pair ARGUMENTS "+server.levelurl" "RUST_SERVER_LEVEL_URL"

else
	add_argument_pair ARGUMENTS "+server.worldsize" "RUST_SERVER_WORLDSIZE"
	add_argument_pair ARGUMENTS "+server.seed" "RUST_SERVER_SEED"
fi

add_argument_pair ARGUMENTS "+server.hostname" "RUST_SERVER_NAME"
add_argument_pair ARGUMENTS "+server.url" "RUST_SERVER_URL"
add_argument_pair ARGUMENTS "+server.headerimage" "RUST_SERVER_BANNER_URL"
add_argument_pair ARGUMENTS "+server.description" "RUST_SERVER_DESCRIPTION"
add_argument_pair ARGUMENTS "+server.maxplayers" "RUST_SERVER_MAXPLAYERS"
add_argument_pair ARGUMENTS "+server.saveinterval" "RUST_SERVER_SAVE_INTERVAL"
add_argument_pair ARGUMENTS "+app.port" "RUST_APP_PORT"

if [ "$RUST_CARBON_ENABLED" = "1" ]; then
	source "$STEAMCMDDIR/rust/carbon/tools/environment.sh"
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$STEAMCMDDIR/rust/RustDedicated_Data/Plugins:$STEAMCMDDIR/rust/RustDedicated_Data/Plugins/x86_64


echo "=========================================================================================="
echo "Launching RustDedicated now! Expect to see a lot of nonsensical gabage log to follow..."
echo "=========================================================================================="

$STEAMCMDDIR/rust/RustDedicated $RUST_STARTUP_COMMAND "${ARGUMENTS[@]}"
exit 0
